name: Posts Daily Check 

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Read recent post and update profile
        uses: ./.github/actions/poststoprofile
      - name: Cat File
        run: |-
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push 
